language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - python setup.py develop
script:
    - python manage.py collectstatic --noinput
    - python manage.py migrate
    - python manage.py test
